### PR TITLE
customize font

### PR DESCRIPTION
**Pull request by amrg101**
it will be nice if one can customize preferences font - color - height ....
if you approve this, I can add others.

### CODE REVIEW

**Comment by MFlisar** [comment]
I would prefer customisation like following:

### 1) Define styles that simple inherit the current style
```
<style name="MaterialPreferences.TextAppearance.Title" parent="TextAppearance.MaterialComponents.Body2">
</style>
```

### 2) use the custom style inside the xml files
```
// remove this line
android:textAppearance="@style/TextAppearance.MaterialComponents.Body2"
// replace it with this line
android:textAppearance="@style/MaterialPreferences.TextAppearance.Title"
```

I think text appearance does support all the font relevat customisation you'd like to have.

Btw. `textAppearanceListItem` resolves to `TextAppearance.Material3.TitleMedium` so this would be the base style for it.
And `textAppearanceListItemSecondary` resolves to `TextAppearance.Material3.BodyMedium` so this would be the base style for it.

I don't want that users are forced to derive from a custom theme nor that they need to provide a custom attribute inside their theme - if  see your approach correctly, your attributes would need to be defined in the app theme

I can add this feature as well though, but if you'd like to do this go ahead.

**Edit**

Actually a better solution would be that the default style of each text derives from the `?attr/textAppearance*` but optionally this can be overwritten globally through the theme by providing a custom style

**Comment by MFlisar** [comment]
By the way one question:

Why don't you change the theme app wide? Do you really want to change fonts inside preferences only and don't want a harmonised style across your whole app?

Have you tried something like following e.g.:

```
 <style name="AppTheme" parent="Theme.Material3.DayNight.NoActionBar">
        <item name="textAppearanceBody2">@style/TextAppearance.App.Body2</item>
        <item name="textAppearanceListItem">@style/TextAppearance.App.ListItem</item>
        <item name="textAppearanceListItemSecondary">@style/TextAppearance.App.ListItemSecondary</item>
    </style>

    <style name="TextAppearance.App.Body2" parent="TextAppearance.MaterialComponents.Body2">
        <item name="fontFamily">sans-serif-condensed-medium</item>
        <item name="android:textSize">14sp</item>
    </style>

    <style name="TextAppearance.App.ListItem" parent="TextAppearance.Material3.TitleMedium">
        <item name="fontFamily">sans-serif-condensed-medium</item>
        <item name="android:textSize">12sp</item>
    </style>

    <style name="TextAppearance.App.ListItemSecondary" parent="TextAppearance.Material3.BodyMedium">
        <item name="fontFamily">sans-serif-condensed-medium</item>
        <item name="android:textSize">10sp</item>
    </style>
```

I actually tried to use appropriate styles everywhere so this approach would be a good alternative...

**Comment by amrg101** [comment]
your approach also works but I prefer my approach at any time. why?

- it uses default font (same as before) unless you choose to override its attributes.
- instead of adding custom style then override it, you only have to override attributes in your app theme.
  this line is all what you need to change title font.
 ` 
       <item name="preferenceTitleFont">@font/font</item>
`
- attributes is library specific which is better because now you can change preference appearance separately and if you want to follow the app style you can simply use the same app style values. instead of being forced to follow the system.
- fully customizable.
- more readable, users can easily understand what these attributes do and of course how to use them.
- easier to maintain, adding new attributes (ex: colors) is better than using custom styles everywhere.

you can add whatever you think is better, will wait for the update :)

**Comment by MFlisar** [comment]
What I want is following:

**Requirement**

```
 <style name="AppTheme" parent="Theme.Material3.DayNight.NoActionBar">
 </style>
```

The above theme must work correctly. I don't want to force the user to define any attributes (even if it is just one) if they just want default material styling everywhere.

**Solution**

I create default styles and use them - you can overwrite them if desired to customise those themes. Default styles always depend on "?attr/..." to depend on the theme attributes by default.

I just committed the change, let me know if this solves your problem. I have "demos" on how to overwrite material styles and how those effect the preferences as well as how to overwrite preference styles only as well - its documented out but all can be found in this file: https://github.com/MFlisar/MaterialPreferences/blob/main/demo/src/main/res/values/styles.xml

If desired you can try it inside your own app like following as well:

```
implementation "com.github.MFlisar.MaterialPreferences:core:2fda0019ab"
...
```

**Declared styleables**

As far as I know, a solution in this direction only works if you use custom views. Would not be much more work, but the custom text view would need to be created and I think its not worth the extra work...

**Comment by amrg101** [comment]
seems great but I have a problem compiling it right now. I think that jitpack has some issues right now.

**Pull request closed without merging**
